---
services:
  neovim:
    image: neovim-playground
    user: "1000:1000"
    volumes:
      - ${HOME}/.config/fish:/home/playground/.config/fish:ro
      - ${PWD}/vim:/home/playground./config/vim:rw
      - neovim-playground:/home/playground/neovim-playground:rw
    tty: true
    stdin_open: true

volumes:
  neovim-playground:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}
